params:
- params.yaml
- reports/params.yaml
stages:
  prepare:
    cmd: 
    - unzip -o input/dataset.zip -d input/dataset
    - unzip -o input/test_dataset.zip -d input/test_dataset
    deps:
    - input/dataset.zip
    outs:
    - input/dataset
  train:
    cmd: python -m steps.train
    deps:
    - steps/train.py
    - banknotes_classifier/modeling
    - banknotes_classifier/training
    - banknotes_classifier/data
    - input/dataset
    outs:
    - artifacts/checkpoints/best-checkpoint.ckpt
    - reports/metrics.json:
        cache: false
  export:
    cmd: python -m steps.export
    deps:
    - steps/export.py
    - artifacts/checkpoints/best-checkpoint.ckpt
    outs:
    - artifacts/model.onnx

  evaluate:
    cmd: python -m steps.evaluate
    deps:
    - steps/evaluate.py
    - artifacts/model.onnx
    - input/test_dataset
    outs:
    -reports/evaluation.json:
        cahce: false
metrics:
- reports/metrics.json
plots:
- reports/plots/metrics:
    x: step
