params:
  - params.yaml
stages:
  prepare:
    cmd: unzip -o input/dataset.zip -d input/dataset
    deps:
    - input/dataset.zip
    outs:
    - input/dataset
  train:
    cmd: python -m steps.train
    deps:
    - steps/train.py
    - banknotes_classifier/modeling
    - banknotes_classifier/training
    - banknotes_classifier/data
    - input/dataset
    params:
    - training
    outs:
    - artifacts/checkpoints/best_checkpoint.ckpt
    - reports/metrics.yaml:
        cache: false
  export:
    cmd: python -m steps.export
    deps:
      - steps/export.py
      - artifacts/checkpoints/best_checkpoint.ckpt
    outs:
      - artifacts/model.onnx


  evaluate:
    cmd: echo "Not implemented yet"
    deps:
    outs:

# metrics:
# - reports/metrics
