params:
  - params.yaml
  - reports/params.yaml
stages:
  prepare:
    cmd:
      - unzip -o input/dataset.zip -d input/dataset > /dev/null 2>&1
      - unzip -o input/test_dataset.zip -d input/test_dataset > /dev/null 2>&1
    deps:
      - input/dataset.zip
    outs:
      - input/dataset
  train:
    cmd: python -m steps.train
    deps:
      - steps/train.py
      - banknotes_classifier/modeling
      - banknotes_classifier/training
      - banknotes_classifier/data
      - input/dataset
    outs:
      - artifacts/checkpoints/best-checkpoint.ckpt
      - reports/training/metrics.json:
          cache: false
  export:
    cmd: python -m steps.export
    deps:
      - steps/export.py
      - artifacts/checkpoints/best-checkpoint.ckpt
    outs:
      - artifacts/model.onnx

  evaluate:
    cmd: python -m steps.evaluate
    deps:
      - steps/evaluate.py
      - artifacts/model.onnx
      - input/test_dataset
    outs:
      - reports/evaluaton/metrics.json:
          cache: false
      - reports/evaluation/plots/confusion_matrix.png:
          cache: false
metrics:
  - reports/evaluation
  - reports/training
plots:
  - reports/plots/metrics:
      x: step
