data:
  dataset_path: /teamspace/studios/this_studio/dataset

training:
  batch_size: 16
  lr: 0.0001

  trainer:
    accelerator: cpu
    max_epochs: 1

  callbacks:
    ModelCheckpoint:
      monitor: valid_loss
      mode: min
      save_top_k: 1
      dirpath: artifacts/checkpoints
      filename: best-checkpoint
    ModelSummary:
      max_depth: 1
    TQDMProgressBar:
      refresh_rate: 1

  logger:
    dir: reports

export:
  model_path: artifacts/model.onnx

