data:
  dataset_path: input/dataset/dataset

training:
  batch_size: 128
  lr: 3e-05

  trainer:
    accelerator: auto
    max_epochs: 20

  callbacks:
    ModelCheckpoint:
      monitor: valid_loss
      mode: min
      save_top_k: 1
      dirpath: artifacts/checkpoints
      filename: best-checkpoint
    ModelSummary:
      max_depth: 1
    TQDMProgressBar:
      refresh_rate: 1

  logger:
    dir: reports

export:
  model_path: artifacts/model.onnx

evaluation:
  test_dataset_path: input/test_dataset/test_dataset
