on:
  push:
    tags:
      - "banknotes_classifier@v*"
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.PAT }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip 
          pip install -r ./requirements.txt
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          prefix: 'banknotes_classifier@v'
          fallback: '0'
        id: get_tag
      - id: generate_image_tag
        shell: bash
        run: |
          echo ${{ steps.get_tag.outputs.tag }} > latest_tag.txt
          version=$(grep -oE '[0-9]+$' latest_tag.txt)
          echo "image_tag=muhammadabdalsattar/banknotes_classifier:v$((version))" >> "$GITHUB_OUTPUT"
      - name: build docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.generate_image_tag.outputs.image_tag }}
