on:
  push:
    tags:
      - "banknotes_classifier@v*"
jobs:
  Deploy_to_HF_Space:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.PAT }}
      - name: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip 
          pip install -r ./requirements.txt

      - id: generate_version
        shell: bash
        run: |
          echo ${{ github.ref_name }} > latest_tag.txt
          version=$(grep -oE '[0-9]+$' latest_tag.txt)
          echo "version=$((version))" >> "$GITHUB_OUTPUT"

      - name: Create New Hugging Face Space
        id: create_hf_space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
        run: |
          # Define the Space name based on the input provided
          SPACE_NAME="banknotes-classifier-V${{ steps.generate_space_version.outputs.version }}"
          python .github/workflows/helpers/hf_spaces.py create-space \
            --space-name $SPACE_NAME \
            --user-name $HF_USERNAME \
            --token $HF_TOKEN \
            --space-sdk docker
          echo "SPACE_NAME=$SPACE_NAME" >> "$GITHUB_OUTPUT"

      - name: configure dvc
        run: |
          echo -E '${{ secrets.GDRIVE_CREDENTIALS_DATA }}' > creds.json
          cat creds.json
          dvc remote add -d -f myremote gdrive://1IdooJif1hoyvpqVNU8zjniOqhMus1Js4
          dvc remote modify myremote gdrive_use_service_account true
          dvc remote modify myremote gdrive_acknowledge_abuse true 
          dvc remote modify myremote --local gdrive_service_account_json_file_path creds.json 

      - name: Download Model
        run: |
          dvc pull artifacts/model.onnx

      - name: Upload App
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
        run: |
          mv -r artiffacts/ app/
          python .github/workflows/helpers/hf_spaces.py upload-folder \
            --space-name ${{ steps.create_hf_space.outputs.SPACE_NAME }} \
            --folder-path app/ \
            --path-in-repo app/ \
            --user-name $HF_USERNAME \
            --token $HF_TOKEN \

          python .github/workflows/helpers/hf_spaces.py create-space-dockerfile \
            --from-file Dockerfile
          
          python .github/workflows/helpers/hf_spaces.py upload-file \
            --space-name ${{ steps.create_hf_space.outputs.SPACE_NAME }} \
            --file-path Dockerfile \
            --path-in-repo Dockerfile \
            --user-name $HF_USERNAME \
            --token $HF_TOKEN \


